// <auto-generated />
namespace PaymentService.Backend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class billingdataset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billingdataset));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171232020_billing data set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
