// <auto-generated />
namespace PaymentService.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class ef600 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ef600));
        
        string IMigrationMetadata.Id
        {
            get { return "201306051344308_ef6.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
