#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class ReservationSummaryPaymentInformation : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"
<div class=""summary_block"">
<h3>Payment information</h3>
<table class=""payment_information_summary"">
<tr>
<td>
Billing name
</td>
<td>Freek Paans</td>
</tr>
<tr>
<td>Billing address</td>
<td>Test<br />13123EN
</td>
</tr>
<tr>
<td>
Credit card number
</td>
<td>
**** **** **** 1234
</td>
</tr>
</table>
</div>");


        }
    }
}
#pragma warning restore 1591
