#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomTypeDetailsService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class RoomTypeSearchResultsDetailsView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\Views\RoomTypeSearchResultsDetailsView.cshtml"

	public RoomTypeDetailsService.WebInterface.ViewModels.RoomTypeDetailsViewModel Model{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral(" \r\n\r\n");


WriteLiteral("\r\n\r\n<div class=\"room_type_details\">\r\n<h3>");


            
            #line 8 "..\..\Views\RoomTypeSearchResultsDetailsView.cshtml"
Write(Model.RoomTypeName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n<p>\r\n<img width=\"100\" height=\"150\" src=\"");


            
            #line 10 "..\..\Views\RoomTypeSearchResultsDetailsView.cshtml"
                              Write(Model.RoomTypeImageUrl);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"roomtype impression\" /> \r\n");


            
            #line 11 "..\..\Views\RoomTypeSearchResultsDetailsView.cshtml"
Write(Model.RoomTypeDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<div class=\"fix\"></div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
