#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomTypeDetailsService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class RoomTypeIDsAvailableView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\Views\RoomTypeIDsAvailableView.cshtml"

	public ICollection<RoomTypeDetailsService.WebInterface.ViewModels.RoomTypeDetailsViewModel> Details{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral(" \r\n\r\n");


WriteLiteral("\r\n\r\n");


            
            #line 7 "..\..\Views\RoomTypeIDsAvailableView.cshtml"
 foreach(var roomType in Details) {


            
            #line default
            #line hidden
WriteLiteral("<div class=\"room_type_details\" roomtypeid=\"");


            
            #line 9 "..\..\Views\RoomTypeIDsAvailableView.cshtml"
                                      Write(roomType.RoomTypeId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n<h3>");


            
            #line 10 "..\..\Views\RoomTypeIDsAvailableView.cshtml"
Write(roomType.RoomTypeName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n<p>\r\n<img width=\"100\" height=\"150\" src=\"");


            
            #line 12 "..\..\Views\RoomTypeIDsAvailableView.cshtml"
                              Write(roomType.RoomTypeImageUrl);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"roomtype impression\" /> \r\n");


            
            #line 13 "..\..\Views\RoomTypeIDsAvailableView.cshtml"
Write(roomType.RoomTypeDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<div class=\"fix\"></div>\r\n</div>\r\n");


            
            #line 17 "..\..\Views\RoomTypeIDsAvailableView.cshtml"

}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
