#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class SelectNonOccupiedRooms : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\Views\SelectNonOccupiedRooms.cshtml"

	public ICollection<Occupancy.WebInterface.ViewModels.RoomViewModel> AvailableRooms{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n\r\n<script src=\"/Scripts/Services/OccupancyService/SelectRoom.js\" type=\"text/jav" +
"ascript\"></script>\r\n\r\n<input type=\"hidden\" name=\"SelectedRoomNumber\" value=\"");


            
            #line 9 "..\..\Views\SelectNonOccupiedRooms.cshtml"
                                                 Write(AvailableRooms.First(r=>r.Selected).RoomNumber);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n");


            
            #line 11 "..\..\Views\SelectNonOccupiedRooms.cshtml"
 foreach(var roomType in AvailableRooms.GroupBy(a=>a.RoomType)) {

            
            #line default
            #line hidden
WriteLiteral("<h4>");


            
            #line 12 "..\..\Views\SelectNonOccupiedRooms.cshtml"
Write(roomType.Key);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");


            
            #line 13 "..\..\Views\SelectNonOccupiedRooms.cshtml"
	
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\SelectNonOccupiedRooms.cshtml"
  foreach(var room in roomType) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<div class=\"selectable_room");


            
            #line 14 "..\..\Views\SelectNonOccupiedRooms.cshtml"
                         Write(room.Selected?" selected":"");

            
            #line default
            #line hidden
WriteLiteral("\" data-roomnumber=\"");


            
            #line 14 "..\..\Views\SelectNonOccupiedRooms.cshtml"
                                                                          Write(room.RoomNumber);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t<a href=\"#\" class=\"select_room\">");


            
            #line 15 "..\..\Views\SelectNonOccupiedRooms.cshtml"
                              Write(room.RoomNumber);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t</div>\r\n");



            
            #line 17 "..\..\Views\SelectNonOccupiedRooms.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\t<div class=\"fix\"></div>\r\n");


            
            #line 19 "..\..\Views\SelectNonOccupiedRooms.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
