// <auto-generated />
namespace GuestService.Backend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class guestschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guestschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171136413_guest schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
