#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITOps.ReservationCustomerEmails.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class ReservationRejectedEmailView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\ReservationRejectedEmailView.cshtml"

	public string Name{get;set;}
	public DateTime ArrivalDate{get;set;}
	public DateTime CheckoutDate{get;set;}
	public Guid ReservationId{get;set;}	
	public string RejectReason{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n<p>\r\nDear ");


            
            #line 12 "..\..\Views\ReservationRejectedEmailView.cshtml"
Write(Name);

            
            #line default
            #line hidden
WriteLiteral(",\r\n</p>\r\n<p>\r\nThank you for your reservation at the ADSD Hotel.\r\n</p>\r\n<p>\r\nUnfor" +
"tunately, we were not able to fulfill your request to reserve a room with us fro" +
"m ");


            
            #line 18 "..\..\Views\ReservationRejectedEmailView.cshtml"
                                                                                  Write(ArrivalDate.ToString("d MMMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" to ");


            
            #line 18 "..\..\Views\ReservationRejectedEmailView.cshtml"
                                                                                                                          Write(CheckoutDate.ToString("d MMMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" because of ");


            
            #line 18 "..\..\Views\ReservationRejectedEmailView.cshtml"
                                                                                                                                                                           Write(RejectReason);

            
            #line default
            #line hidden
WriteLiteral(".\r\n</p>\r\n<p>\r\nIf you have any questions, don\'t hesitate to contact us. Your reser" +
"vation number is ");


            
            #line 21 "..\..\Views\ReservationRejectedEmailView.cshtml"
                                                                               Write(ReservationId);

            
            #line default
            #line hidden
WriteLiteral(".\r\n</p>\r\n<p>\r\nRegards,<br />\r\nThe ADSD Hotel Staff\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
