// <auto-generated />
namespace ReservationService.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class _2reservationentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2reservationentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201306061213456_2 reservation entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
