// <auto-generated />
namespace ReservationService.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class reservedat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reservedat));
        
        string IMigrationMetadata.Id
        {
            get { return "201305202053226_reserved at"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
