#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class ReservationDetailsForm : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 5 "..\..\Views\ReservationDetailsForm.cshtml"

	public CustomerWebsite.Events.ObtainingReservationDetails Model{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral(" \r\n\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n\r\n\r\n<div>\r\n<h3>Please enter your details</h3>\r\n<form action=\"");


            
            #line 12 "..\..\Views\ReservationDetailsForm.cshtml"
         Write(Model.SubmitUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"reservation_details_form\">\r\n<input type=\"hidden\" name=\"Reservation.Reser" +
"vationId\" value=\"");


            
            #line 13 "..\..\Views\ReservationDetailsForm.cshtml"
                                                        Write(Model.ReservationId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n<input type=\"submit\" value=\"Go to confirmation screen\" />\r\n<script src=\"/Sc" +
"ripts/Services/ReservationService/ReservationDetailsForm.js\" type=\"text/javascri" +
"pt\"></script>\r\n</form>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
