#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class SearchRoomsBox : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Views\SearchRoomsBox.cshtml"

    public ReservationService.WebInterface.Models.SearchParameters Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {
WriteLiteral(" ");



WriteLiteral(" \r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<script src=\"/Scripts/ReservationService/SearchBox.js\" type=\"text/javascript\"" +
"></script>\r\n\r\n<form action=\"/Rooms/Search\">\r\nFrom: <input type=\"text\" name=\"sear" +
"ch_from\" value=\"");


            
            #line 11 "..\..\Views\SearchRoomsBox.cshtml"
                                               Write(Model!=null?Model.From.ToString("MM/dd/yyyy"):null);

            
            #line default
            #line hidden
WriteLiteral("\"/> Till <input value=\"");


            
            #line 11 "..\..\Views\SearchRoomsBox.cshtml"
                                                                                                                           Write(Model!=null?Model.Till.ToString("MM/dd/yyyy"):null);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text\" name=\"search_till\" />\r\n<input type=\"submit\" value=\"");


            
            #line 12 "..\..\Views\SearchRoomsBox.cshtml"
                        Write(Model!=null?"Search again":"Search");

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</form>");


        }
    }
}
#pragma warning restore 1591
