#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class SearchResultsView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 5 "..\..\Views\SearchResultsView.cshtml"

	public ReservationService.WebInterface.ViewModels.SearchResultsViewModel Model{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral(" \r\n\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n\r\n<div class=\"search_results\">\r\n<h3>Found ");


            
            #line 10 "..\..\Views\SearchResultsView.cshtml"
     Write(Model.RoomTypeIds.Count);

            
            #line default
            #line hidden
WriteLiteral(" rooms!</h3>\r\n\r\n<ul class=\"search_room_results\">\r\n");


            
            #line 13 "..\..\Views\SearchResultsView.cshtml"
 foreach(var roomTypeId in Model.RoomTypeIds) {

            
            #line default
            #line hidden
WriteLiteral("\t<li>\r\n\t\t<div id=\"");


            
            #line 15 "..\..\Views\SearchResultsView.cshtml"
      Write(roomTypeId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"room_item\">\r\n\t\t<div class=\"reserve_room_form\">\r\n\t\t<form action=\"/Reserva" +
"tion/Start\" method=\"post\">\r\n\t\t\t<input type=\"hidden\" name=\"roomTypeId\" value=\"");


            
            #line 18 "..\..\Views\SearchResultsView.cshtml"
                                            Write(roomTypeId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\t\t\t<input type=\"hidden\" name=\"from\" value=\"");


            
            #line 19 "..\..\Views\SearchResultsView.cshtml"
                                      Write(Model.From.ToString("o"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\t\t\t<input type=\"hidden\" name=\"till\" value=\"");


            
            #line 20 "..\..\Views\SearchResultsView.cshtml"
                                      Write(Model.Till.ToString("o"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\t\t\t<input class=\"book_room_btn\" type=\"submit\" value=\"Book now!\" />\r\n\t\t</for" +
"m>\r\n\t\t</div>\r\n\t\t</div>\r\n\t\t<div class=\"fix\"></div>\r\n\t</li>\r\n");


            
            #line 27 "..\..\Views\SearchResultsView.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
