#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestService.WebInterface.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class ReservationSummaryGuestInformation : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n<div class=\"summary_block\">\r\n<h3>Guest information</h3>\r\n<table>\r\n<tr>\r\n<td>N" +
"ame</td><td>Freek Paans</td>\r\n</tr>\r\n<tr>\r\n<td>Email</td><td>freek@infi.nl</td>\r" +
"\n</tr>\r\n<tr>\r\n<td>Phonenumber</td><td>06131312</td>\r\n</tr>\r\n</table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
